version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    environment:
      JAVA_HOME: /usr/local/openjdk-17
      PATH: /usr/local/openjdk-17/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    working_directory: ~/frontend

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      # Restore Gradle cache
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "frontend/gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-

      # Download and set up dependencies
      - run:
          name: Install dependencies
          command: cd frontend && ./gradlew dependencies

      # Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "frontend/gradle/wrapper/gradle-wrapper.properties" }}

      # Run the build to check if it compiles
      - run:
          name: Build APK
          command: cd frontend && ./gradlew assembleDebug

      # Store the APK as an artifact (optional)
      - store_artifacts:
          path: frontend/app/build/outputs/apk/debug
          destination: apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
