version: 2.1

jobs:
  build:
    working_directory: ~/frontend
    docker:
      - image: circleci/android:api-30 # Or the appropriate image you’re using
    steps:
      - checkout

      # Adjust paths for caching
      - restore_cache:
          keys:
            - gradle-{{ checksum "frontend/build.gradle" }}
            - gradle-

      # Run the build
      - run:
          name: Build with Gradle
          command: ./gradlew assembleDebug

      # Run unit tests
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

      # Cache Gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "frontend/build.gradle" }}

      # Store test results and APK
      - store_test_results:
          path: frontend/app/build/test-results
      - store_artifacts:
          path: frontend/app/build/outputs/apk/debug
