version: 2.1

jobs:
  build:
    docker:
      # Using a prebuilt CircleCI Docker image for Android
      - image: circleci/android:api-30

    environment:
      # Cache dependencies
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m -Dkotlin.incremental=false"
      _JAVA_OPTIONS: "-Xmx4096m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

    steps:
      - checkout # Checkout the code

      # Restore the Gradle cache
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-

      # Run Gradle build
      - run:
          name: Build with Gradle
          command: ./gradlew assembleDebug

      # Run unit tests
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

      # Store Gradle cache
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}

      # Save the test results
      - store_test_results:
          path: app/build/test-results

      # Store the built APK
      - store_artifacts:
          path: app/build/outputs/apk/debug
